server:
  # 设置服务器端口
  port: 80
  servlet:
    # 设置项目根路径
    context-path: /

spring:
  # 配置Redis
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 服务器端口
    port: 6379
    # Redis密码
    # password: ******
    jedis:
      pool:
        # 最大连接数（负数表示没有限制）
        max-active: 8
        # 最大空闲连接
        max-idle: 8
        # 最小空闲链接
        min-idle: 0
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: 1ms
    # 链接超时时间（毫秒）
    # 此参数设置过小导致的，将这个参数设值得更大些，如200或以上！
    #  timeout 这个在实际的生产环境中非常有用
    timeout: 50ms

  # 配置MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # 这里有必要添加时区信息，会报错
    url: jdbc:mysql://localhost:3306/mybatis_relation?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&useUnicode=true

#mybatis-plus
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: net.gaox.model
  typeEnumsPackage: net.gaox.model.model.enums
  #  typeAliasesPackage: net.gaox.model.entity
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
#  global-config:
#    # 数据库相关配置
#    db-config:
#      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
#      id-type: auto
#      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
#      field-strategy: not_empty
#      #驼峰下划线转换
#      #      column-underline: true
#      #数据库大写下划线转换
#      capital-mode: false
#      #逻辑删除配置
#      logic-delete-value: 0
#      logic-not-delete-value: 1
#      db-type: mysql
#      table-underline: true
#    #刷新mapper 调试神器
#    refresh: true
#  # 原生配置
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false

#控制项目日志级别
logging:
  level:
    net:
      gaox:
        model: debug