server:
  port: 12606
  servlet:
    context-path: /

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/iot?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&useUnicode=true
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: gaox
        group: home

mybatis-plus:
  typeAliasesPackage: net.gaox.domain.entity
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level.net.gaox.base: debug
