spring:
  profiles:
    active: dev
---
spring:
  profiles: local
server:
  port: 10001
---
spring:
  profiles: dev
server:
  port: 12511
---
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
live-chat:
  tcp:
    port: 8090
  boss:
    thread:
      count: 2
  worker:
    thread:
      count: 2
  so:
    keepalive: true
    backlog: 100