# 服务器端口配置
server:
  port: 12517

# 日志配置文件地址
logging:
  config: classpath:log4j/log4j2.yml

#mybatis-plus配置
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: net.gaox.designation
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  # 配置MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cron?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&useUnicode=true&tinyInt1isBit=false
    # Hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5